language: c
compiler:
  - gcc
  - clang
env:
  - DYNAMIPS_ARCH=amd64
  - DYNAMIPS_ARCH=x86
  - DYNAMIPS_ARCH=nojit
# Change this to your needs
before_install: sudo apt-get update -qq
install:
  - test "$DYNAMIPS_ARCH" != "x86" && sudo apt-get install -qq binutils && sudo apt-get install -qq gcc g++ libelf-dev uuid-dev libpcap0.8-dev
  - test "$DYNAMIPS_ARCH" = "x86" && sudo apt-get install -qq binutils:i386 && sudo apt-get install -qq gcc:i386 g++:i386 libelf-dev:i386 uuid-dev:i386 libpcap0.8-dev:i386
before_script:
  - mkdir build
  - cd build
script:
  - cmake -DDYNAMIPS_ARCH=$DYNAMIPS_ARCH -DANY_COMPILER=1 -DCMAKE_INSTALL_PREFIX=$(pwd)/test ..
  - make install
