language: c
compiler:
  - gcc
  - clang
env:
  - DYNAMIPS_ARCH=amd64 ARCH=:amd64 CMAKE_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
  - DYNAMIPS_ARCH=x86   ARCH=:i386  CMAKE_LIBRARY_PATH=/usr/lib/i386-linux-gnu
  - DYNAMIPS_ARCH=nojit ARCH=       CMAKE_LIBRARY_PATH=
before_install:
  - sudo dpkg
  - sudo apt-get update -qq
install:
  - sudo apt-get install -q libelf-dev$ARCH
  - sudo apt-get install -q uuid-dev$ARCH
  - sudo apt-get install -q libpcap0.8-dev$ARCH
before_script:
  - mkdir build
  - cd build
script:
  - cmake -DDYNAMIPS_ARCH=$DYNAMIPS_ARCH -DANY_COMPILER=1 -DCMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH -DCMAKE_INSTALL_PREFIX=$(pwd)/test ..
  - make install
