platform:
    - x86

environment:
    global:
        CYG_ROOT: C:/cygwin
        CYG_CACHE: C:/cygwin/var/cache/setup
        CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
        CC: gcc
    matrix:
        - CYG_ARCH: x86

install:
    - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P make -P gcc-core -P cmake >NUL'
    - 'appveyor DownloadFile http://www.mr511.de/software/libelf-0.8.13.tar.gz'
    - 'mkdir libelf && tar xvzf libelf-0.8.13.tar.gz -C libelf'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER/libelf/libelf-0.8.13 && ./configure && make && make install'

build_script:
    - '%CYG_ROOT%/bin/bash -lc "ls $APPVEYOR_BUILD_FOLDER'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER && mkdir -p build'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER/build && cmake ..'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER/build && make'

artifacts:
  - path: 'build/stable/dynamips.exe'
